app:
  name: "auth-starterkit-be"
  server_name: "Auth Starterkit"
  version: "0.0.1"
  environment: "development"

  server:
    host: "localhost"
    port: "3010"
    cors: "{url},{url}"
    url: ""

  redis:
    host: "localhost"
    port: "6379"
    password: "{password}"

  mongodb:
    host: "localhost"
    port: "27017"
    username: "{username}"
    password: "{password}"
    database: ""

  postgresql:
    host: "localhost"
    port: "5432"
    username: "{username}"
    password: "{password}"
    database: ""

  minio:
    host: "localhost"
    port: "9000"
    access_key: "{access_key}"
    secret_key: "{secret_key}"

  jwt:
    public: ""
    private: ""
    remember_token_public: ""
    remember_token_private: ""
    guest_session_secret: ""

  discord:
    token: "{token}"

  secret:
    auth_key: ""
    remember_token_key: ""
    data_encryption_key: ""