app:
  name: "auth-starterkit-be"
  server_name: "Auth Starterkit"
  version: "0.0.1"
  environment: "production"

  server:
    host: "{host}"
    port: "3010"
    cors: "{url},{url}"

  redis:
    host: "{host}"
    port: "6379"
    password: "{password}"

  mongodb:
    host: "{host}"
    port: "27017"
    username: "{username}"
    password: "{password}"
    database: ""

  postgresql:
    host: "{host}"
    port: "5432"
    username: "{username}"
    password: "{password}"
    database: ""

  minio:
    host: "{host}"
    port: "9000"
    access_key: "{access_key}"
    secret_key: "{secret_key}"

  jwt:
    public: ""
    private: ""

  discord:
    token: "{token}"